/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    news: News;
    tags: Tag;
    pages: Page;
    unduhan: Unduhan;
    tabel: Tabel;
    'download-leads': DownloadLead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    unduhan: UnduhanSelect<false> | UnduhanSelect<true>;
    tabel: TabelSelect<false> | TabelSelect<true>;
    'download-leads': DownloadLeadsSelect<false> | DownloadLeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'landing-page': LandingPage;
    'visi-misi': VisiMisi;
    manajemen: Manajeman;
    navbar: Navbar;
    footer: Footer;
    'contact-us': ContactUs;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'landing-page': LandingPageSelect<false> | LandingPageSelect<true>;
    'visi-misi': VisiMisiSelect<false> | VisiMisiSelect<true>;
    manajemen: ManajemenSelect<false> | ManajemenSelect<true>;
    navbar: NavbarSelect<false> | NavbarSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'contact-us': ContactUsSelect<false> | ContactUsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  description: string;
  /**
   * Upload an SVG or PNG icon for this product (recommended: SVG, square format)
   */
  icon?: (number | null) | Media;
  /**
   * Link to the Riplay document or page
   */
  riplayUrl?: string | null;
  /**
   * Link to the SPPA document for download
   */
  sppaUrl?: string | null;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Short summary shown in news cards and previews.
   */
  excerpt?: string | null;
  status: 'draft' | 'published';
  date: string;
  /**
   * Select existing tags or create new ones.
   */
  tags?: (number | Tag)[] | null;
  /**
   * URL-friendly identifier. Auto-filled from the title.
   */
  slug?: string | null;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Short summary shown in previews.
   */
  excerpt?: string | null;
  status: 'draft' | 'published';
  /**
   * URL-friendly identifier. Auto-filled from the title.
   */
  slug?: string | null;
  image?: (number | null) | Media;
  /**
   * Add structured blocks (e.g. Timeline) below the main content.
   */
  layout?:
    | {
        items: {
          /**
           * e.g. "March 25, 2011"
           */
          date: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'timeline';
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "unduhan".
 */
export interface Unduhan {
  id: number;
  title: string;
  /**
   * Teks penjelasan singkat di bawah judul halaman.
   */
  description?: string | null;
  status: 'draft' | 'published';
  /**
   * URL-friendly identifier. Auto-filled from the title.
   */
  slug?: string | null;
  /**
   * Jika aktif, pengguna harus memasukkan email sebelum mengunduh PDF. Link akan dikirimkan ke email mereka.
   */
  requireEmailGate?: boolean | null;
  /**
   * Setiap seksi tampil sebagai satu item accordion yang dapat dibuka.
   */
  sections?:
    | {
        /**
         * Label kecil di atas judul, mis. "Klaim", "Polis".
         */
        category: string;
        title: string;
        description?: string | null;
        items?:
          | {
              name: string;
              type: 'pdf' | 'link';
              /**
               * Upload file PDF ke media library.
               */
              file?: (number | null) | Media;
              /**
               * URL untuk link eksternal atau PDF yang tidak di-upload.
               */
              href?: string | null;
              /**
               * Tampilan ukuran, mis. "245 KB". Kosongkan untuk auto-hitung dari file.
               */
              size?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tabel".
 */
export interface Tabel {
  id: number;
  title: string;
  /**
   * Teks penjelasan singkat di bawah judul halaman.
   */
  description?: string | null;
  status: 'draft' | 'published';
  /**
   * URL-friendly identifier. Auto-filled from the title.
   */
  slug?: string | null;
  tables?:
    | {
        /**
         * Label kecil di atas judul, mis. "Produk", "Layanan".
         */
        category: string;
        title: string;
        description?: string | null;
        /**
         * Daftar kolom dari kiri ke kanan. Urutan ini harus sama dengan urutan sel di setiap baris.
         */
        columns?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Jumlah sel tiap baris harus sama dengan jumlah kolom di atas.
         */
        rows?:
          | {
              cells?:
                | {
                    value?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Email yang dikumpulkan dari form unduh PDF.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "download-leads".
 */
export interface DownloadLead {
  id: number;
  email: string;
  fileName?: string | null;
  fileUrl?: string | null;
  unduhan?: (number | null) | Unduhan;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'unduhan';
        value: number | Unduhan;
      } | null)
    | ({
        relationTo: 'tabel';
        value: number | Tabel;
      } | null)
    | ({
        relationTo: 'download-leads';
        value: number | DownloadLead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  riplayUrl?: T;
  sppaUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  excerpt?: T;
  status?: T;
  date?: T;
  tags?: T;
  slug?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  excerpt?: T;
  status?: T;
  slug?: T;
  image?: T;
  layout?:
    | T
    | {
        timeline?:
          | T
          | {
              items?:
                | T
                | {
                    date?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "unduhan_select".
 */
export interface UnduhanSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  status?: T;
  slug?: T;
  requireEmailGate?: T;
  sections?:
    | T
    | {
        category?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              name?: T;
              type?: T;
              file?: T;
              href?: T;
              size?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tabel_select".
 */
export interface TabelSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  status?: T;
  slug?: T;
  tables?:
    | T
    | {
        category?: T;
        title?: T;
        description?: T;
        columns?:
          | T
          | {
              label?: T;
              id?: T;
            };
        rows?:
          | T
          | {
              cells?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "download-leads_select".
 */
export interface DownloadLeadsSelect<T extends boolean = true> {
  email?: T;
  fileName?: T;
  fileUrl?: T;
  unduhan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page".
 */
export interface LandingPage {
  id: number;
  hero?: {
    descriptionDesktop?: string | null;
    descriptionMobile?: string | null;
    whatsappUrl?: string | null;
    ctaPrimaryLabel?: string | null;
    ctaPrimaryHref?: string | null;
    ctaSecondaryLabel?: string | null;
  };
  promoStrip?: {
    heading?: string | null;
    buttonLabel?: string | null;
    buttonHref?: string | null;
  };
  productsSection?: {
    badge?: string | null;
    heading?: string | null;
  };
  whyChooseUs?: {
    badge?: string | null;
    heading?: string | null;
    description?: string | null;
    reasons?:
      | {
          iconName:
            | 'Car'
            | 'Home'
            | 'Plane'
            | 'Shield'
            | 'Anchor'
            | 'Banknote'
            | 'Flame'
            | 'HardHat'
            | 'Award'
            | 'Trophy'
            | 'MapPin'
            | 'Zap';
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
    image?: (number | null) | Media;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  newsSection?: {
    badge?: string | null;
    heading?: string | null;
  };
  ctaBanner?: {
    heading?: string | null;
    subtext?: string | null;
    primaryLabel?: string | null;
    primaryHref?: string | null;
    whatsappUrl?: string | null;
    contactAddress?: string | null;
    contactPhone?: string | null;
    contactEmail?: string | null;
    backgroundImage?: (number | null) | Media;
    actionCards?:
      | {
          icon: 'whatsapp' | 'envelope' | 'agen' | 'car' | 'phone';
          label: string;
          sublabel?: string | null;
          href?: string | null;
          useWhatsappUrl?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visi-misi".
 */
export interface VisiMisi {
  id: number;
  pageTitle?: string | null;
  pageSubtitle?: string | null;
  featuredImage?: (number | null) | Media;
  visi?: {
    title?: string | null;
    content?: string | null;
  };
  misi?: {
    title?: string | null;
    items?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  valuesTitle?: string | null;
  valuesSubtitle?: string | null;
  values?:
    | {
        /**
         * Satu huruf, mis. S, A, H, A, B, A, T
         */
        letter: string;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manajemen".
 */
export interface Manajeman {
  id: number;
  pageTitle?: string | null;
  pageSubtitle?: string | null;
  highlights?:
    | {
        icon?: ('Star' | 'Target' | 'Users' | 'Shield' | 'TrendingUp' | 'Trophy') | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  boardOfCommissioners?: {
    title?: string | null;
    members?:
      | {
          photo?: (number | null) | Media;
          name: string;
          position: string;
          id?: string | null;
        }[]
      | null;
  };
  boardOfDirectors?: {
    title?: string | null;
    members?:
      | {
          photo?: (number | null) | Media;
          name: string;
          position: string;
          id?: string | null;
        }[]
      | null;
  };
  tataKelola?: {
    title?: string | null;
    subtitle?: string | null;
    columns?:
      | {
          content: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar".
 */
export interface Navbar {
  id: number;
  items?:
    | {
        label: string;
        href: string;
        dropdownItems?:
          | {
              title: string;
              description?: string | null;
              href: string;
              subItems?:
                | {
                    title: string;
                    href: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  upperColumns?:
    | {
        title?: string | null;
        content?:
          | (
              | {
                  links?:
                    | {
                        label: string;
                        href: string;
                        icon?:
                          | (
                              | 'none'
                              | 'car'
                              | 'home'
                              | 'shield'
                              | 'plane'
                              | 'star'
                              | 'check'
                              | 'arrowRight'
                              | 'phone'
                              | 'mail'
                              | 'mapPin'
                              | 'file'
                            )
                          | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'linkList';
                }
              | {
                  companyName?: string | null;
                  subheading?: string | null;
                  items?:
                    | {
                        type: 'phone' | 'email' | 'address' | 'whatsapp';
                        value: string;
                        displayText?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'contactInfo';
                }
              | {
                  content?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'textContent';
                }
              | {
                  image: number | Media;
                  href?: string | null;
                  width?: number | null;
                  height?: number | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'imageContent';
                }
              | {
                  line1?: string | null;
                  line2?: string | null;
                  accentLine?: ('none' | 'line1' | 'line2') | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'badge';
                }
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  lowerFooter?: {
    links?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    socialLinks?:
      | {
          platform: 'facebook' | 'twitter' | 'instagram' | 'linkedin' | 'youtube' | 'tiktok';
          href: string;
          id?: string | null;
        }[]
      | null;
    copyrightText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us".
 */
export interface ContactUs {
  id: number;
  pageTitle?: string | null;
  pageSubtitle?: string | null;
  sectionTitle?: string | null;
  sectionSubtitle?: string | null;
  /**
   * Kartu kontak yang ditampilkan di halaman (telepon, WA, email, dll)
   */
  channels?:
    | {
        iconType: 'phone' | 'whatsapp' | 'email' | 'form';
        title: string;
        description: string;
        /**
         * Contoh: tel:02150508080, https://wa.me/622150508080, mailto:info@..., atau #form-pengaduan
         */
        href?: string | null;
        hrefLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Upload a .ico, .png, or .svg file. Recommended size: 32×32 px.
   */
  favicon?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page_select".
 */
export interface LandingPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        descriptionDesktop?: T;
        descriptionMobile?: T;
        whatsappUrl?: T;
        ctaPrimaryLabel?: T;
        ctaPrimaryHref?: T;
        ctaSecondaryLabel?: T;
      };
  promoStrip?:
    | T
    | {
        heading?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  productsSection?:
    | T
    | {
        badge?: T;
        heading?: T;
      };
  whyChooseUs?:
    | T
    | {
        badge?: T;
        heading?: T;
        description?: T;
        reasons?:
          | T
          | {
              iconName?: T;
              title?: T;
              body?: T;
              id?: T;
            };
        image?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  newsSection?:
    | T
    | {
        badge?: T;
        heading?: T;
      };
  ctaBanner?:
    | T
    | {
        heading?: T;
        subtext?: T;
        primaryLabel?: T;
        primaryHref?: T;
        whatsappUrl?: T;
        contactAddress?: T;
        contactPhone?: T;
        contactEmail?: T;
        backgroundImage?: T;
        actionCards?:
          | T
          | {
              icon?: T;
              label?: T;
              sublabel?: T;
              href?: T;
              useWhatsappUrl?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visi-misi_select".
 */
export interface VisiMisiSelect<T extends boolean = true> {
  pageTitle?: T;
  pageSubtitle?: T;
  featuredImage?: T;
  visi?:
    | T
    | {
        title?: T;
        content?: T;
      };
  misi?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  valuesTitle?: T;
  valuesSubtitle?: T;
  values?:
    | T
    | {
        letter?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manajemen_select".
 */
export interface ManajemenSelect<T extends boolean = true> {
  pageTitle?: T;
  pageSubtitle?: T;
  highlights?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  boardOfCommissioners?:
    | T
    | {
        title?: T;
        members?:
          | T
          | {
              photo?: T;
              name?: T;
              position?: T;
              id?: T;
            };
      };
  boardOfDirectors?:
    | T
    | {
        title?: T;
        members?:
          | T
          | {
              photo?: T;
              name?: T;
              position?: T;
              id?: T;
            };
      };
  tataKelola?:
    | T
    | {
        title?: T;
        subtitle?: T;
        columns?:
          | T
          | {
              content?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navbar_select".
 */
export interface NavbarSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        dropdownItems?:
          | T
          | {
              title?: T;
              description?: T;
              href?: T;
              subItems?:
                | T
                | {
                    title?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  upperColumns?:
    | T
    | {
        title?: T;
        content?:
          | T
          | {
              linkList?:
                | T
                | {
                    links?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          icon?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              contactInfo?:
                | T
                | {
                    companyName?: T;
                    subheading?: T;
                    items?:
                      | T
                      | {
                          type?: T;
                          value?: T;
                          displayText?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              textContent?:
                | T
                | {
                    content?: T;
                    id?: T;
                    blockName?: T;
                  };
              imageContent?:
                | T
                | {
                    image?: T;
                    href?: T;
                    width?: T;
                    height?: T;
                    id?: T;
                    blockName?: T;
                  };
              badge?:
                | T
                | {
                    line1?: T;
                    line2?: T;
                    accentLine?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        id?: T;
      };
  lowerFooter?:
    | T
    | {
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        socialLinks?:
          | T
          | {
              platform?: T;
              href?: T;
              id?: T;
            };
        copyrightText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us_select".
 */
export interface ContactUsSelect<T extends boolean = true> {
  pageTitle?: T;
  pageSubtitle?: T;
  sectionTitle?: T;
  sectionSubtitle?: T;
  channels?:
    | T
    | {
        iconType?: T;
        title?: T;
        description?: T;
        href?: T;
        hrefLabel?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  favicon?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}